package com.examplez.demo.controller;

import com.examplez.demo.model.Game;
import com.examplez.demo.storage.GameFileManager;
import com.examplez.demo.storage.GameState;
import com.examplez.demo.storage.exceptions.GameLoadException;
import com.examplez.demo.storage.exceptions.GameSaveException;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.ChoiceDialog;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;
import java.util.List;
import java.util.Optional;

/**
 * Controls the initial menu and starts or resumes a match.
 */
public class StartController {

    /** Normal game mode in which enemy ships remain hidden. */
    private static final String PLAYER_MODE = "Player";

    /** Verification mode in which enemy ships are visible for testing. */
    private static final String VERIFIER_MODE = "Verifier";

    /** Field used to enter or display the commander's nickname. */
    @FXML
    private TextField playerNameField;

    /** Primary button used to start a new match. */
    @FXML
    private Button startGameButton;

    /** Contextual validation message displayed below the nickname field. */
    @FXML
    private Label labelName;

    /** Button used to resume the active saved match. */
    @FXML
    private Button loadGameButton;

    /** Label that reports whether a saved campaign is available. */
    @FXML
    private Label statusLabel;

    /**
     * Initializes the menu according to the current persistent-save status.
     */
    @FXML
    public void initialize() {
        boolean hasSavedGame = GameFileManager.hasValidSave();
        loadGameButton.setDisable(!hasSavedGame);

        if (hasSavedGame) {
            GameState state = GameFileManager.loadGame();
            playerNameField.setText(state.getNickname());
            statusLabel.setText("SAVED CAMPAIGN DETECTED // " + state.getNickname().toUpperCase());
        } else {
            statusLabel.setText("NO SAVED CAMPAIGN DETECTED");
        }
    }

    /**
     * Validates the nickname, optionally replaces an existing save and opens
     * the placement screen.
     *
     * @param event event generated by the start button
     */
    @FXML
    public void handleStartGame(ActionEvent event) {
        String playerName = playerNameField.getText().trim();
        if (playerName.isEmpty()) {
            labelName.setText("IDENTIFY YOURSELF, COMMANDER.");
            playerNameField.requestFocus();
            return;
        }

        if (GameFileManager.hasValidSave() && !confirmSaveReplacement()) {
            return;
        }

        try {
            GameFileManager.deleteGame();
            changeGameView(event, askTypeOfUser(), playerName);
        } catch (IOException | GameSaveException exception) {
            showError("NEW MATCH ERROR", "The new match could not be opened.", exception);
        }
    }

    /**
     * Loads the active saved match and opens the combat screen directly.
     *
     * @param event event generated by the load button
     */
    @FXML
    public void handleLoadGame(ActionEvent event) {
        loadSavedGameAndTransition(event);
    }

    /**
     * Displays a confirmation before a new match overwrites the current save.
     *
     * @return {@code true} when the player confirms replacement
     */
    private boolean confirmSaveReplacement() {
        Alert alert = new Alert(Alert.AlertType.CONFIRMATION);
        alert.setTitle("Replace Saved Campaign");
        alert.setHeaderText("An active battle is already saved.");
        alert.setContentText("Starting a new game will permanently replace that progress.");

        Optional<ButtonType> result = alert.showAndWait();
        return result.isPresent() && result.get() == ButtonType.OK;
    }

    /**
     * Loads a complete snapshot and configures the combat controller.
     *
     * @param event event used to locate the current stage
     */
    private void loadSavedGameAndTransition(ActionEvent event) {
        try {
            GameState state = GameFileManager.loadGame();
            FXMLLoader loader = new FXMLLoader(
                    getClass().getResource("/com/examplez/demo/play-match-view.fxml")
            );
            Parent root = loader.load();

            Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
            stage.setScene(new Scene(root, 1280, 800));
            stage.setTitle("Naval Battle // Combat");
            stage.setResizable(false);
            stage.centerOnScreen();

            PlayController controller = loader.getController();
            controller.restoreSession(state);
            stage.show();
        } catch (GameLoadException | IOException exception) {
            loadGameButton.setDisable(true);
            statusLabel.setText("SAVED CAMPAIGN UNAVAILABLE");
            showError("LOAD GAME ERROR", "The saved campaign could not be restored.", exception);
        }
    }

    /**
     * Asks which visibility mode should be used for the new match.
     *
     * @return selected mode, defaulting to {@value #PLAYER_MODE}
     */
    public String askTypeOfUser() {
        ChoiceDialog<String> dialog = new ChoiceDialog<>(
                PLAYER_MODE,
                List.of(PLAYER_MODE, VERIFIER_MODE)
        );
        dialog.setTitle("Game Mode");
        dialog.setHeaderText("Select the fleet visibility mode.");
        dialog.setContentText("Mode:");
        return dialog.showAndWait().orElse(PLAYER_MODE);
    }

    /**
     * Creates a new model and opens the fleet-placement screen.
     *
     * @param event      event used to locate the current stage
     * @param userType   selected visibility mode
     * @param playerName validated player nickname
     * @throws IOException if the placement FXML cannot be loaded
     */
    private void changeGameView(ActionEvent event, String userType, String playerName)
            throws IOException {
        FXMLLoader loader = new FXMLLoader(
                getClass().getResource("/com/examplez/demo/place-ships-view.fxml")
        );
        Parent root = loader.load();

        PlacementController controller = loader.getController();
        controller.initGame(new Game(), playerName, userType);

        Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        stage.setScene(new Scene(root, 1200, 800));
        stage.setTitle("Naval Battle // Fleet Deployment");
        stage.setResizable(false);
        stage.centerOnScreen();
        stage.show();
    }

    /**
     * Displays a user-facing error dialog.
     *
     * @param title     short error title
     * @param message   explanatory error message
     * @param exception underlying failure
     */
    private void showError(String title, String message, Exception exception) {
        exception.printStackTrace();
        Alert alert = new Alert(Alert.AlertType.ERROR);
        alert.setTitle(title);
        alert.setHeaderText(message);
        alert.setContentText(exception.getMessage());
        alert.showAndWait();
    }
}
